FROM nginx:alpine

# Frontend-Dateien kopieren
COPY index.html /usr/share/nginx/html/
COPY auth-service/ /usr/share/nginx/html/auth-service/
COPY shopping-service/ /usr/share/nginx/html/shopping-service/
COPY checkout-service/ /usr/share/nginx/html/checkout-service/

# Nginx-Konfiguration kopieren
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
