version: '3.8'
services:
  mongo:
     image: mongo
     ports:
       - "27017:27017"
     volumes:
       - mongo_data:/data/db
       - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
     environment:
       MONGO_INITDB_DATABASE: shopping
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: rootpass
     command: ["--auth"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  shopping-service:
    build: ./shopping-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - kafka
    environment:
      JWT_SECRET: supergeheimespasswort
  checkout-service:
    build: ./checkout-service
    depends_on:
      - kafka

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://authuser:authpass@mongo:27017/auth_db?authSource=auth_db
      MONGO_DB: auth_db
      MONGO_COLLECTION: users
      JWT_SECRET: supergeheimespasswort
      JWT_EXPIRY: 3600
    
    restart: unless-stopped

volumes:
  mongo_data:

