name: CI Pipeline (Build | Test | Build Images -> GHCR)

on:
  push:
    branches: [ main, Arnold-Branch ]  # Beide Branches
  pull_request:
    branches: [ main, Arnold-Branch ]  # Beide Branches
  workflow_dispatch:

env:
  GO_VERSION: 1.24.5

jobs:
  build-test:
    name: Build & Test Go services
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [shopping-service, checkout-service, auth-service]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Prepare & tidy
        run: |
          cd ${{ matrix.service }}
          go mod tidy

      - name: Build
        run: |
          cd ${{ matrix.service }}
          go build ./...

      - name: Run unit tests
        run: |
          cd ${{ matrix.service }}
          go test ./... -v

  docker-build:
    name: Build and push images to GHCR
    needs: build-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [shopping-service, checkout-service, auth-service]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:${{ github.sha }}
YAML